@baseUrl = http://localhost:3002

### Get all pacotes
GET {{baseUrl}}/api/pacotes

### Inserir pacote

POST {{baseUrl}}/api/pacotes
Content-Type: application/json

{
    "titulo": "Pacote Promocional",
    "descricao": "Inclui vários serviços com desconto",
    "servicosIds": [14, 15],
    "desconto": 50
}

### Get Pacote especifico
GET {{baseUrl}}/api/pacotes/2

### Alterar pacote
PUT {{baseUrl}}/api/pacotes/11
Content-Type: application/json

{
    "titulo": "Pacote Atualizado",
    "descricao": "Descrição atualizada para o pacote",
    "servicosIds": [1, 3], 
    "desconto": 30
}

### Deletar pacote
DELETE {{baseUrl}}/api/pacotes/10
